version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"
    volumes:
      - .:/code
    networks:
      - mynetwork
    depends_on:
      - db


  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - mynetwork

  telegram_bot:
    build: ../tel_chat_bot
    environment:
      - ENVIRONMENT_VARIABLE=value
    networks:
      - mynetwork

  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - mynetwork