# Generated by Django 4.1.5 on 2023-03-02 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AluminiumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=30)),
                ('value', models.FloatField(default=0)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=30)),
                ('value', models.IntegerField(default=0)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=30)),
                ('value', models.IntegerField(default=0)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=30)),
                ('value', models.FloatField(default=0)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MountingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mounting_system', models.CharField(max_length=30)),
                ('value', models.IntegerField(default=0)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lamp', models.CharField(max_length=70)),
                ('value_profile', models.FloatField(default=0)),
                ('value_module', models.FloatField(default=0)),
                ('value_driver', models.IntegerField(default=0)),
                ('value_cover', models.IntegerField(default=0)),
                ('value_mounting_system', models.IntegerField(default=0)),
                ('use_cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.cover')),
                ('use_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.driver')),
                ('use_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.lightmodule')),
                ('use_mounting_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.mountingsystem')),
                ('use_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.aluminiumprofile')),
            ],
        ),
        migrations.CreateModel(
            name='History_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=15)),
                ('value', models.FloatField(default=0)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
