# Generated by Django 4.1.5 on 2023-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AluminiumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MountingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mounting_system', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
