# Generated by Django 4.1.5 on 2023-01-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='drivers',
            new_name='driver',
        ),
    ]
