# Generated by Django 4.1.5 on 2023-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_log',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
