# Generated by Django 4.1.5 on 2023-02-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lamp', models.CharField(max_length=70)),
                ('value_profile', models.IntegerField(default=0)),
                ('value_module', models.IntegerField(default=0)),
                ('value_driver', models.IntegerField(default=0)),
                ('value_cover', models.IntegerField(default=0)),
                ('value_mounting_system', models.IntegerField(default=0)),
                ('use_cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.cover')),
                ('use_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.driver')),
                ('use_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.lightmodule')),
                ('use_mounting_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.mountingsystem')),
                ('use_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.aluminiumprofile')),
            ],
        ),
    ]
