# Generated by Django 4.1.5 on 2023-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_lamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='value_module',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='value_profile',
            field=models.FloatField(default=0),
        ),
    ]
